### ISSUE TITLE
doesnt work version on 3.52

### ISSUE THREAD

**Issue by neco2211** [ama6nen/INZERNAL#11]

**Comment by ama6nen** [comment]
Its not hard to update the version yourself the source, and new update is coming soon which will fix it.
Will close issue when I commit the update.

**Comment by yEsPaP** [comment]
i personally still use 3.51 gt but edited to 3.52 in source. works fine

**Comment by neco2211** [comment]
@ama6nen ofc i did change to version 3.52 when i run gt it gets stuck
