### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by Needheelp** [ama6nen/INZERNAL#12]
I watched your tutorial and did all same things but I cant modify punch speed for example. Seems like I only can modify the game version. Also where i can open that imgui design?

**Comment by ama6nen** [comment]
Menu opens with F2, and most things are modifiable in the menu now. (Gonna make update vid at some point since the one now is outdated)
Punch speed can be modified from the source [here](https://github.com/ama6nen/INZERNAL/blob/main/INZERNAL/core/globals.cpp#L47)

**Comment by Needheelp** [comment]
Got gui open and things seem to work well. Only fast punch is still not working edited already that to smaller value I also tried to edit it from gui but I still dont see any difference.

it says:
 C:\Users\myusername\Desktop\INZERNAL-0.5\bin\INZERNAL.dll 
 C:\Users\myusername\Desktop\INZERNAL-0.5\bin\INZERNAL.dll is not a 
 valid Win32 application.   But im pretty sure that doesnt cause the problem because the dll still builds to that folder. Im also sure that I have right debug settings
 Im just wondering why fast punch doesnt work even i change the value (changing speed and other things works normally)

**Comment by Needheelp** [comment]
And I have one more question to bother with (sorry :D) Im so dumb that I cant get even custom flag mode working...


enum FlagMode {
	fmKeep = 0,		//keep your flag
	fmRandom = 0,	//pick random flag from gt folder
	fmCustom = 1,	//use custom flag

std::string	flag		= "hu";		//set if flag_mode is set to fmCustom

I have set those like that but it is still giving me random flags ( I want hungary flag )

**Comment by HertZxD** [comment]
set this to fmCostum
on [Here](https://github.com/ama6nen/INZERNAL/blob/main/INZERNAL/core/globals.cpp#L31)

**Comment by Needheelp** [comment]
> set this to fmCostum
> on [Here](https://github.com/ama6nen/INZERNAL/blob/main/INZERNAL/core/globals.cpp#L31)

Oh ya got it now :D thanks
I wanna remind you guys that im not a programmer so i cant know everything so dont irriated

**Comment by HertZxD** [comment]
> I wanna remind you guys that im not a programmer so i cant know everything. Dont get irriated please :)

i know :)
