### ISSUE TITLE
Injector doesn't work

### ISSUE THREAD

**Issue by poxq** [ama6nen/INZERNAL#13]
i built the thing and did everything you said but it doesn't work it gets stuck on injecting proccess is there any fix on this?

**Comment by ama6nen** [comment]
Try downloading it from [here](https://github.com/ama6nen/INZERNAL/releases/tag/V0.5)
If you dont have admin perms then use the patcher instead, it doesnt need admin unlike the injector.

**Comment by poxq** [comment]
yeah that fixed it thanks
