### ISSUE TITLE
How should i open the menu

### ISSUE THREAD

**Issue by Pugax** [ama6nen/INZERNAL#24]
Yes i have injected it and no problem with that but i do not know how do i open that menu. It opens second window of growtopia (Actually command prompt where it says that it is injected) But when i go back to gt, there is no menu like on your pictures

**Comment by heysurfer** [comment]
F2 [discussions](https://github.com/ama6nen/INZERNAL/discussions)

**Comment by IProgramInNig3r** [comment]
press alt-f4
