### ISSUE TITLE
en tiiä mikä homma mut

### ISSUE THREAD

**Issue by Tomijoo** [ama6nen/INZERNAL#26]
ei toimi uusin inzernal jostaa kumma syyst peli vaa aukee ja sammuu en tiiä mikä homma ku ei ennenkää oo ollu mitää ongelmii

**Comment by ama6nen** [comment]
Fixed dl from [here](https://github.com/ama6nen/INZERNAL/releases/tag/V0.6Beta) again,
if it doesn't work with the patcher then use injector, patcher does not seem to work for some ppl
