### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Beerusas** [ama6nen/INZERNAL#3]

**Comment by Beerusas** [comment]
![paveikslas](https://user-images.githubusercontent.com/74473837/99158206-0941d480-26d9-11eb-8b50-b70ff7ff6626.png)

**Comment by Beerusas** [comment]
Last thing beforce gt crashes

**Comment by ama6nen** [comment]
Use the versions its meant to be used for, all info is in readme

**Comment by Beerusas** [comment]
okay it works, but it doesn't open gui anymore
