### ISSUE TITLE
nazi slime got patched ez

### ISSUE THREAD

**Issue by Tomijoo** [ama6nen/INZERNAL#30]

**Comment by TheLenx** [comment]
nazi slime patched in 10 minute lol

**Comment by IProgramInNig3r** [comment]
noooooo, the best feature got patched fucc

**Comment by TheLenx** [comment]
ripp i loved that fetaure ♥

**Comment by Elixirrr** [comment]
yeah, also bubble spam not working anymore

**Comment by Gangsteri** [comment]
Spam does work but i found that for me it only works when the menu is open.

**Comment by undestinedx** [comment]
tomi gimme edited dll for subserver crasher

**Comment by ama6nen** [comment]
> Spam does work but i found that for me it only works when the menu is open.

Will fix in next update, does not work because its in menu 




Also removing slime nazi in next update if its patched
