### ISSUE TITLE
Can't open the menu

### ISSUE THREAD

**Issue by undestinedx** [ama6nen/INZERNAL#34]
Hey everything works. It had mod zoom as default but I can't open the menu. Tried F2 and Fn + F2.

**Comment by Tomijoo** [comment]
close game and inject again

**Comment by Gangsteri** [comment]
You need to have the game focused when you inject or it doesnt work.

**Comment by undestinedx** [comment]
Still doesnt work. And what do you mean focused? no other window or app open?

**Comment by Gangsteri** [comment]
If u dont know what focused window means, i would highly reconsider even using inzernal.

**Comment by undestinedx** [comment]
> If u dont know what focused window means, i would highly reconsider even using inzernal.

You literally just said "focused" on your reply. That's why I was asking if you meant focused windows :)

**Comment by ama6nen** [comment]
Will add old imgui method later as backup, closing
