### ISSUE TITLE
Version bypass got patched

### ISSUE THREAD

**Issue by IProgramInNig3r** [ama6nen/INZERNAL#39]
https://prnt.sc/xz0939 

oof

**Comment by wh1ter0se69** [comment]
> https://prnt.sc/xz0939 
> 
> 
> 
> oof

still works with proxy

**Comment by IProgramInNig3r** [comment]
i was talking about inzernal tho

**Comment by wh1ter0se69** [comment]
> i was talking about inzernal tho

yes I know that, I'm just stating it in case you want to continue doing whatever it is you're doing

**Comment by ama6nen** [comment]
I will add option that will automatically detect newest version from this message and add config so you can modify it later on yourself.
