### ISSUE TITLE
the imgui menu isn't working.

### ISSUE THREAD

**Issue by iiLeafy** [ama6nen/INZERNAL#5]
eyo, so i wanted to open up the imgui menu right, i patch it yeah, open it log on, try to press f2 nothing happens, changed f2 to insert still doesnt work so idk bro.

**Comment by ama6nen** [comment]
Does it say failed to create device in the console?

And I cant really do anything without extra info

**Comment by SSebia** [comment]
I have noticed that issue as well, it says nothing in the console, and restarting Growtopia a few times will fix it.

**Comment by ama6nen** [comment]
Are you injecting with injector or using the patched exe?
I think it might fail on creating d3d device

**Comment by ama6nen** [comment]
Fixed some issues with imgui, not sure if your issue was fixed but for me all imgui related issues have been fixed, make another issue if it persists
