### ISSUE TITLE
Sigs

### ISSUE THREAD

**Issue by mfmosp** [ama6nen/INZERNAL#58]
How do i update sigs? I have 0 info about sigs. (also about what they are)

UPD: I learned that we find them with hex editors, but still don't know how to find new sigs.

**Comment by mfmosp** [comment]
solved

**Comment by GoodPog** [comment]
atleast explain how

**Comment by mfmosp** [comment]
they updated sigs just try to reinstall the project and compile it.

**Comment by GoodPog** [comment]
i know but still i want an idea so i could atleast do something about future sigs

**Comment by mfmosp** [comment]
u can make it with hxd editor or like cheat engine but idk how
