### ISSUE TITLE
Still i cant open menu i have idea

### ISSUE THREAD

**Issue by iProB1** [ama6nen/INZERNAL#62]
how can i make auto opens menu when injected its will be usable for me can someone help

**Comment by qatroxx** [comment]
did you ever tried to read some text?

**Comment by qatroxx** [comment]
https://github.com/ama6nen/INZERNAL/blob/4fc590c0d8c9f4b1206355e93667e98338fe1da9/INZERNAL/core/globals.cpp#L78

**Comment by NoneGT** [comment]
bro nvm it
I formatted my pc
now its OK.
