### ISSUE TITLE
Inzernal is fixed ( I guess? )

### ISSUE THREAD

**Issue by gangsterGT** [ama6nen/INZERNAL#71]
The game crashes once you try logging to the game with login spoof and i think version bypass is finally patched or theres something wrong with other stuff thats getting spoofed.

**Comment by qatroxx** [comment]
use 3.62 growtopia version

**Comment by gangsterGT** [comment]
Where can i find 3.62 or 3.61 without any bullshit?

**Comment by qatroxx** [comment]
https://prnt.sc/153b0e1 lazy to send so try ask friends or someone if they has

**Comment by HertZxD** [comment]
the sigs still working on 3.63, just update the ProcessTankUpdate thing

**Comment by aurhack** [comment]
> the sigs still working on 3.63, just update the ProcessTankUpdate thing

Wdym, where?

**Comment by aurhack** [comment]
> the sigs still working on 3.63, just update the ProcessTankUpdate thing

okay i found it, what i do now? what i change?
