### ISSUE TITLE
3.64 softfixed inzernal, guessing sigs.cpp has to be changed?

### ISSUE THREAD

**Issue by cuckling** [ama6nen/INZERNAL#77]

**Comment by HertZxD** [comment]
nope
just use version 3.64

if u still want to use 3.63, then change the version on global.cpp to 3.63

**Comment by gangsterGT** [comment]
the game crashes when i trade with someone, or when someone uses a consumable, inzernal is kinda broken

**Comment by cuckling** [comment]
> nope
> just use version 3.64
> 
> if u still want to use 3.63, then change the version on global.cpp to 3.63

ive tried practically everything
using versions 3.61 ranging to 3.64 and whenever i logged in both growtopia and inzernal crashed
my main concern was maybe the hex in sigs.cpp but that also didnt seem to do anything,
pretty confused as to why it doesnt work atm.

**Comment by ama6nen** [comment]
Im not sure because I dont use it myself anymore but if you are using patcher then it will at least crash because of mutex bypass being broken, comment the gt::patch_mutex() in dllmain

**Comment by cuckling** [comment]
dont worry about it. the problem ended up being the spoof version string. the update made it so that you had to spoof to 3.63 and not 3.66.

**Comment by ama6nen** [comment]
You need to new parameter to tileextra::serialize, int version, if version is 3.64 it will crash otherwise

ex:
```
void __cdecl hooks::TileExtra_Serialize(TileExtra* te, uint8_t* mem, uint32_t* pos, bool save1, World* world, bool save2, Tile* target, int version) {
    static auto orig = decltype(&hooks::TileExtra_Serialize)(hookmgr->orig(sig::tileextra_serialize));
    orig(te, mem, pos, save1, world, save2, target, version); 
```

**Comment by ama6nen** [comment]
Nvm I fixed it myself, should be working now
