### ISSUE TITLE
Growtopia crashes because of segmentation violation(Inzernal is detected)

### ISSUE THREAD

**Issue by gangsterGT** [ama6nen/INZERNAL#79]
Here is a screenshot of the crash report: https://prnt.sc/16mha9k
As i said on the title, gt crashes because inzernal accessed a memory location that was not assigned to it.
Ubipoggers is taking action against public cheats i guess 
Everything here is pasted and detected n1gg33rs

**Comment by GoodPog** [comment]
ah ig thats why ama made it private

**Comment by ama6nen** [comment]
https://github.com/ama6nen/INZERNAL/issues/77#issuecomment-867724653

**Comment by ama6nen** [comment]
Nothing is pasted and fixed it now
