### ISSUE TITLE
How Can I print anything to the game?

### ISSUE THREAD

**Issue by promanasd** [ama6nen/INZERNAL#83]

**Comment by teocoder** [comment]
something like this

```cpp
variantlist vlist{ "OnConsoleMessage" };
vlist[1] = "log message";

gt::send_varlist(vlist);
```

**Comment by promanasd** [comment]
> something like this
> 
> ```c++
> variantlist vlist{ "OnConsoleMessage" };
> vlist[1] = "log message";
> 
> gt::send_varlist(vlist);
> ```

thanks for the help
