### ISSUE TITLE
Assertion Fail Issue!

### ISSUE THREAD

**Issue by zhiyuanwang123** [ama6nen/INZERNAL#9]
Saying wrong tile size while build

build method: msbuild /p:AllowUnsafeBlocks=true

Saying: Tile.h(71,28): error C2338: wrong tile size!

**Comment by z1xto** [comment]
Hmm, maybe try to use your head?

**Comment by Zavins** [comment]
@z1xto Huh? What's wrong then. I couldn't find error

**Comment by Zavins** [comment]
@z1xto Please help me if you know

**Comment by Zavins** [comment]
ehhh nevermind. It worked after i restart vs

Thanks a lot

**Comment by zhiyuanwang123** [comment]
Worked After I reconfigured VS

**Comment by zhiyuanwang123** [comment]
Saying: Tile.h(71,28): error C2338: wrong tile size!
This issue occurs when you build in x86. x64 doesn't have this issue.

However, there is imgui issue during the runtime.

![image](https://user-images.githubusercontent.com/39817104/102727139-f03ccc80-42f1-11eb-99bb-add5603a6fdd.png)

**Comment by ama6nen** [comment]
Does it occur both on release and debug?
And yes, building on x86 will not work.

**Comment by zhiyuanwang123** [comment]
Yes, both release and debug has that issue, and also, do plan to fix the proxy? Seems like GT has a protocol change.

**Comment by zhiyuanwang123** [comment]
The new version fixed it. Thanks!
